### ISSUE TITLE
Move python modules at project root to a module's folder.

### ISSUE THREAD

**Issue by LeeBergstrand** [Metannotate/Metannotate#3]
#### Problem Description:

Current many python modules are located at the root of the directory. However, only one python script ```run_metannotate.py``` is from the CLI. Having all these modules in a ```modules``` folder would help developer productivity and on-boarding velocity since developer would only need to look at one place to find the start of code execution.

#### Problem Solution:

Move additional Python modules to a ```modules``` folder.

![current file structure 2](https://user-images.githubusercontent.com/5819462/29285040-082ca11a-80fb-11e7-8cc7-435777d744fd.png)

**Comment by LeeBergstrand** [comment]
@RoranDangerous I would recommend that you use Pycharm's refactor feature https://www.jetbrains.com/help/pycharm/refactoring-source-code.html

You can click on the file and then right-click refactor move and it will make sure all the links in your python code (in ```run_metannotate.py``` ) are updated.

**Comment by RoranDangerous** [comment]
Done

**Comment by RoranDangerous** [comment]
Fixed
