### ISSUE TITLE
Add a requirements.txt file.

### ISSUE THREAD

**Issue by LeeBergstrand** [Metannotate/Metannotate#5]
#### Problem Description:

Currently pip packages are installed one packages at a time in ```base_installation.sh```.

```Shell
echo "Installing python packages through pip.\n"
pip=`which pip`
if [ -e ~/.local/bin/pip ] ; then
  pip=~/.local/bin/pip
fi
sudo $pip install --user numpy --ignore-installed
sudo $pip install --user celery --ignore-installed
sudo $pip install --user taxtastic --ignore-installed
sudo $pip install --user lxml --ignore-installed
sudo $pip install --user python-gflags --ignore-installed
sudo $pip install --user ete2 --ignore-installed
```

Rather than being installed line by line all the requirements should be placed in a ```requirements.txt``` file. Putting documentation in a ```requirements.txt``` allows us to easily determine which python packages are required and at what versions. Inside a requirements file.

```
MyApp
Framework==0.9.4
Library>=0.2
```

#### Problem Solution:

Create a requirements.txt file. See this documentation [here](https://pip.readthedocs.io/en/1.1/requirements.html).

#### Gotchas:

- Make sure you are installing software using pip3 or pip2.
- ```taxtastic``` may need to be installed via pip2.
- Use ```pip install --user``` but do not use sudo because this does not require sudo.

**Comment by RoranDangerous** [comment]
Kyle created requirements.txt file. Can you take a look and let me know if I need to modify it?

**Comment by LeeBergstrand** [comment]
This file should be on its own pull request.

**Comment by RoranDangerous** [comment]
Added in the pull request.

**Comment by LeeBergstrand** [comment]
@RoranDangerous I forgot to mention this in my review. Each package line should specify the latest version of the package on ```pypi```. Like this: 

```
Framework==0.9.4
```
