### ISSUE TITLE
Install dependancies via Linuxbrew.

### ISSUE THREAD

**Issue by LeeBergstrand** [Metannotate/Metannotate#6]
#### Problem Description:

Currently many of the CLI dependancies are installed in the following manner:

```Shell
echo "Installing HMMER & Easel mini-applications.\n"
if [ ! `which hmmsearch` ] | [ ! `which esl-sfetch` ] ; then
  cd downloads
  wget "http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2-linux-intel-x86_64.tar.gz" #updated address here
  tar -xzf hmmer-3.1b2-linux-intel-x86_64.tar.gz
  cd hmmer*
  ./configure
  make
  cp -R . "$software"/hmmer/
  ln -s "$software"/hmmer/binaries/hmmstat ~/.local/bin/hmmstat
  ln -s "$software"/hmmer/binaries/hmmsearch ~/.local/bin/hmmsearch
  ln -s "$software"/hmmer/binaries/hmmalign ~/.local/bin/hmmalign
  ln -s "$software"/hmmer/binaries/esl-reformat ~/.local/bin/esl-reformat
  ln -s "$software"/hmmer/binaries/esl-sfetch ~/.local/bin/esl-sfetch
  cd $metAnnotateDir
fi
```

Ultimately, installation script like these can and will break over time.

#### Proposed Solution:

We can use [linuxbrew](http://linuxbrew.sh) and [homebrew-science](https://github.com/Homebrew/homebrew-science) to install these pieces of software.

**Comment by LeeBergstrand** [comment]
Okay, 

So we can use the following packages homebrew-science science packages.

| Dependancies 	| Homebrew Science Formula                                             	| Comments                                                                                                                        	|
|--------------	|----------------------------------------------------------------------	|---------------------------------------------------------------------------------------------------------------------------------	|
| FastTreeMP   	| https://github.com/Homebrew/homebrew-science/blob/master/fasttree.rb 	| By default homebrew builds the multithreaded version. Additionally, the binary might be called FastTree rather than FastTreeMP. 	|
| EMBOSS       	| https://github.com/Homebrew/homebrew-science/blob/master/emboss.rb   	|                                                                                                                                 	|
| HMMER        	| https://github.com/Homebrew/homebrew-science/blob/master/hmmer.rb    	| Does not install easel mini-applications (https://github.com/EddyRivasLab/easel)                                                	|

We need to build brew formula for the following:

| Dependancies 	| Github Repo                           	| Comments                                            	|
|--------------	|---------------------------------------	|-----------------------------------------------------	|
| EASEL        	| https://github.com/EddyRivasLab/easel 	|                                                     	|
| placer       	| https://github.com/matsen/pplacer     	| Guppy and placer are located in the same code base. 	|
| guppy        	| https://github.com/matsen/pplacer     	| Guppy and placer are located in the same code base. 	|

**Comment by LeeBergstrand** [comment]
The other software is shipped with the repo! or are installed python packages...

**Comment by RoranDangerous** [comment]
I am trying to figure out how to install dependencies separately form the the whole library. In EMBOSS we need transeq only, but brew install installs the whole library and it takes a while.

**Comment by LeeBergstrand** [comment]
@RoranDangerous I wouldn't worry about that. Pre-mature optimization. For example in the current install it downloads all of EMBOSS.

```shell
echo "Installing EMBOSS transeq.\n"
if [ ! `which transeq` ] ; then
  cd downloads
  wget "ftp://emboss.open-bio.org/pub/EMBOSS/old/6.5.0/EMBOSS-6.5.7.tar.gz"
  tar -xzf EMBOSS-6.5.7.tar.gz
  cd EMBOSS*
  ./configure --without-x
  make
  cp -R emboss/ "$software"/
  ln -s "$software"/emboss/transeq ~/.local/bin/transeq
  cd $metAnnotateDir
fi
```

**Comment by LeeBergstrand** [comment]
Summery:

- We created a homebrew formula for easel.
- We still install pplacer and guppy from binaries.
