### ISSUE TITLE
Old and new MetAnnotate results do not agree

### ISSUE THREAD

**Issue by jmtsuji** [Metannotate/Metannotate#71]
# Problem description
I've tested pre-release 0.9.1 in a Docker container on a dataset that I have analyzed previously using the original MetAnnotate.

Results match for _pmoA_ and _mcrA_ (functional marker genes), which have small results tables.

However, results differ markedly for _rpoB_ (taxonomic marker gene with many hits):
- Although the total line count of both tables match, the new table is about half the size of the old table:
```
4.8M	rpoB_2_all_annotations_fSooJ8781503658.tsv <- new
8.4M	rpoB_5_all_annotations_M9smVz92660494.tsv <- old
```
- The new file contains many more 'unclassified' reads than the old:
```
$ grep -c "unclassified" rpoB_2*.tsv rpoB_5*.tsv 
rpoB_2_all_annotations_fSooJ8781503658.tsv:35039
rpoB_5_all_annotations_M9smVz92660494.tsv:9494
```
- Classifications do not match for corresponding ORFs, e.g. (line 2),
```
# New
Dataset	HMM Family	ORF	HMM E-val	Aligned Length	Closest Homolog	%id of Closest Homolog	Closest Homolog Species	Closest Homolog Genus	Closest Homolog Family	Closest Homolog Order	Closest Homolog Class	Closest Homolog Phylum	Closest Homolog Superkingdom
1_Lake_227_2013_6_m_SS4_assembled_frag_0	rpoB_2	HWI-1KL153_108_HC2WVBCXX_2_2207_3787_42174_1_245_ma447_1_to_81	1.4e-55	81	gi|16802304|ref|NP_463789.1|	80.2	Listeria monocytogenes	Listeria	Listeriaceae	Bacillales	Bacilli	Firmicutes	Bacteria

# Old
Dataset	HMM Family	ORF	HMM E-val	Aligned Length	Closest Homolog	%id of Closest Homolog	Closest Homolog Species	Closest Homolog Genus	Closest Homolog Family	Closest Homolog Order	Closest Homolog Class	Closest Homolog Phylum	Closest Homolog Superkingdom
1_Lake_227_2013_6_m_SS4_assembled_frag_0	rpoB_5	HWI-1KL153_108_HC2WVBCXX_2_2207_3787_42174_1_245_ma447_1_to_81	1.4e-55	81	gi|948087109|ref|WP_056745841.1|	100.0	Acidovorax sp. Root568	Acidovorax	Comamonadaceae	Burkholderiales	Betaproteobacteria	Proteobacteria	Bacteria
```

# Troubleshooting
- It appears that something went wrong with the RefSeq database search. The cached MSA for rpoB contains a mere 32 sequence:
```
$ grep -c "^>" 726ef10e59b5a5a58ff57349607708a925ca01adb8e09b71.converted.msa
34
```
- The Refseq database file itself (Refseq.fa) looks okay, however -- same size (19 G) as with the old MetAnnotate. Both contain the same number of entries (60539900)

# Potential problem areas
- Could this be due to the fact that Refseq.fa has been moved from the MetAnnotate/data folder to a user-defined folder in the new MetAnnotate? Are there any calls in the code that are specific to MetAnnotate/data?
- Alternatively, could MetAnnotate somehow be stuck calling the ReferenceTest.fa test database file?

**Comment by LeeBergstrand** [comment]
@jmtsuji Did you run the tests first? It could be caching the results for ```ReferenceTest.fa``` in the cache file. Then when your ran it with the real ```RefSeq.fa``` it used the cache file because the cache file is present.

**Comment by jmtsuji** [comment]
Indeed -- clearing the cache fixed the issue. I'll add a line of code to test_metannotate_end_to_end.sh to clear the cache once the test is finished. Long-term, we'll need to change the way that UUID's of cached files are generated so that the reference database is taken into account.
