### ISSUE TITLE
More than one hmm and orfs

### ISSUE THREAD

**Issue by tpellegrinetti** [Metannotate/Metannotate#75]
Hi all,
I would like to know what the format of the list of orfs and hmm should look like when I want to use more than one orf and more than one hmm profile.

I've tried several ways and it's giving an error.
Could someone provide me with an template?

Thanks.

**Comment by jmtsuji** [comment]
@tpellegrinetti I believe that a comma-separated list of file paths is needed by MetAnnotate, e.g.,

```bash
orf_list="orf_files/dataset_1.faa,orf_files/dataset_2.faa"
hmm_list="hmm_files/my_hmm_1.hmm,hmm_files/my_hmm_2.hmm"
db="data/Refseq.fa"
outdir=[ your output directory of choice ]

mkdir -p "${outdir}/tmp"

python2.7 run_metannotate.py \
  --orf_files="${orf_list}" \
  --hmm_files="${hmm_list}" \
  --reference_database="${db}" \
  --output_dir="${outdir}" \
  --tmp_dir="${outdir}/tmp" \
  --run_mode=sequence
```

I am not sure if absolute filepaths are required for the ORF and HMM files or if relative paths (as I have shown) are okay.

As an alternative, you could try to use the Docker container version of MetAnnotate mentioned [here in the develop branch](https://github.com/MetAnnotate/MetAnnotate/tree/develop#recommended-docker-installation-for-command-line-and-soon-web-gui). A shell script wrapper, `metannotate-wrapper-docker`, was included that just requires the paths to the directories containing all ORF and HMM files.

Unfortunately, MetAnnotate is no longer being actively developed or maintained, so support for MetAnnotate is fairly limited. Still, I hope the above advice is helpful.

**Comment by tpellegrinetti** [comment]
Hi @jmtsuji thank you for your reply.

I am using a server of my university, so I can't use the docker.

I believe that this code that you answer will be useful to me.

**Comment by jmtsuji** [comment]
@tpellegrinetti Glad this helps -- that makes sense that you can't use Docker. If you run into further trouble with MetAnnotate, you can try installing from the develop branch, where some work was done to try to stabilize the installation process. All the best.
